### ISSUE TITLE
Unstyled demo does not work

### ISSUE THREAD

**Issue by alesdotio** [jkneb/ember-crud#3]
when clicking a user you get 

```
Cannot call method 'fromNow' of null (index):279
```

probably might want to check that moment(date) is not null here:

```
Em.Handlebars.registerBoundHelper('formatDate', function(date){
    return moment(date).fromNow();
});
```

**Comment by jkneb** [comment]
I can't reproduce the problem. Give me some more data :)

**Comment by alesdotio** [comment]
1. http://jkneb.github.io/ember-crud/unstyled/#/users
2. click on "Dean Winchester"
3. nothing happens, got error in console

latest chrome on osx lion

**Comment by jkneb** [comment]
Weird. Every thing is good for me. (same os and browser than you)

Try to clear the localStorage maybe? But, if it solves the problem, I don't know what went wrong the first time.

**Comment by alesdotio** [comment]
Clearing localStorage fixed the problem. Maybe I messed the data up somehow in the styled version before going to the unstyled one. Can't reproduce it anymore.

Unrelated: might want to handle the case when visiting a non-existing user http://jkneb.github.io/ember-crud/unstyled/#/users/33

Great app, and great tutorial though ;)
