### ISSUE TITLE
gunt watch

### ISSUE THREAD

**Issue by connor11528** [jkneb/ember-crud#4]
I forked the project and am trying to run it. After installing the sass gem I ran

```
$ grunt watch
Running "watch" task
Waiting...
```

I waited for 30 min and nothing happened.

I then tried

`grunt sass`
`grunt emberTemplates`
`grunt concat`

and they each worked right away. Why not `grunt watch`?

**Comment by jkneb** [comment]
:D indeed. It is waiting for you to modify a file. 

Julien
