### ISSUE TITLE
Not working in chrome

### ISSUE THREAD

**Issue by Rajavelu** [jkneb/ember-crud#5]
The demo http://jkneb.github.io/ember-crud/#/users is not working in chrome to me.
please refer the attached image
![ember-crud](https://f.cloud.github.com/assets/3033600/2434370/086375e4-adb1-11e3-9c74-1f835d2aa27f.png)

**Comment by jkneb** [comment]
I would say it's a GPU issue? Could you go on this page http://codepen.io/jkneb/full/qJBIl and tell me if the cube is actually in 3D or if it is "flat".

**Comment by Rajavelu** [comment]
@jkneb : Thank you, It shows as "flat".

**Comment by jkneb** [comment]
ok so it's a hardware issue :) i used a lot a 3D transforms CSS and it seems you computer doesn't support it. Sorry for that. I encourage you to see the "unstyled" demo if you want to learn Ember  http://jkneb.github.io/ember-crud/unstyled

**Comment by Rajavelu** [comment]
@jkneb : Thanks again. But I have a doubt, If it is hardware issue, then how it is working fine in firefox?(My OS: ubuntu-12.04). Also i tried in windows, working fine in firefox & chrome, but not in IE.

**Comment by jkneb** [comment]
Really? weird i'll investigate!

**Comment by Rajavelu** [comment]
Unsupported(to ubuntu) graphics card(which is supported to windows) enabled in my system as default. After disable that graphics card, works fine :) .

**Comment by jkneb** [comment]
Cool!
