### ISSUE TITLE
Regarding Error: Something you did caused a view to re-render after it rendered but before it was inserted into the DOM.

### ISSUE THREAD

**Issue by rameshkts** [jkneb/ember-crud#6]
Hi 
I am new to emberjs.I developing one small application Like yours Ember-CRUD.
I am facing one issue like this
Error: Something you did caused a view to re-render after it rendered but before it was inserted into the DOM.
## /_The following these errors_/

Error: You cannot modify child views while in the inBuffer state

Emptying a view in the inBuffer state is not allowed and should not happen under normal circumstances. Most likely there is a bug in your application. This may be due to excessive property change notifications.

---

I dont know how to resolve this.Please help me regarding this.

**Comment by jkneb** [comment]
Please put your code in a Gist so I can tell you what's wrong.

J

**Comment by rameshkts** [comment]
My code there was an extra div tag there.That's why it cause that problem.

**Comment by jkneb** [comment]
Ah! Yeah I know that closing tag... :)
